### ISSUE TITLE
Microsoft Defender collector is not working properly

### ISSUE THREAD

**Issue by SamuelHassine** [OpenBAS-Platform/collectors#45] opened 2024-10-17 08:53 UTC
## Description

Microsoft Defender collector is not working properly

Atomic testing: https://filigran.obas.filigran.io/admin/atomic_testings/84152f4f-16d4-4210-9d2c-a9cc5052393d

Alert in Defender center: https://security.microsoft.com/incident2/2607/overview?tid=f2a29c7e-5230-41d3-b5d1-4b6e2c4e6b7c

=> Nothing is displayed in the results.

**Comment by EllynBsc** [comment] 2024-10-28 10:44
Duplicate of [#1685](https://github.com/OpenBAS-Platform/openbas/issues/1685)

**Closed as not planned by EllynBsc** 2024-10-28 10:44 UTC
Labels: bug, duplicate
